# Site settings
baseurl: "/vn"
asseturl: "/assets"
name: "tAgiAu"
skin: "classic"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: "\n\n"
paginate: 12
paginate_path: "/page:num"