# Site settings
baseurl: "/vn"
asseturl: "/assets"
name: "tAgiAu"
skin: "classic"
lang:
 read_more: "... read more"

# Build settings
# markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->
paginate: 3
paginate_path: /page:num